### ISSUE TITLE
Somewhat strange function interface

### ISSUE THREAD

**Issue by ysimonson** [mtabini/go-waitqueue#2]
This constructor: https://github.com/mtabini/go-waitqueue/blob/master/queue.go#L119

seems to have a somewhat strange interface to me. Why the separation between `queueName` and `additionalQueueNames`? I can't follow from the code why it'd be necessary, and it makes the API somewhat strange to use, e.g. in one of our internal apps: `waitqueue.NewBounded(cfg.GetMaxConcurrentIndexes(), categoryMappingKeys[0], categoryMappingKeys[1:]...)`

**Comment by ysimonson** [comment]
Ping @ian-axelrod

**Comment by ian-axelrod** [comment]
This is a common approach in API design to signify that at least one argument is required, but multiple extra arguments of the same type are allowed. It ensures that errors in the use of the interface get caught at compile time.

**Comment by ysimonson** [comment]
I see, that makes sense. @mtabini does this seem sufficiently golang-like?

**Comment by mtabini** [comment]
Yep. 👍

**Comment by ysimonson** [comment]
Cool, will close.
