### ISSUE TITLE
Naming of `BoundedMutuallyExclusiveWaitQueue`

### ISSUE THREAD

**Issue by ysimonson** [mtabini/go-waitqueue#3]
Should it be called a `BoundedMutuallyExclusiveWaitQueue`? To me, that seems to signify that it's a mutex lock, not an read-write mutex lock. Maybe `BoundedWaitQueue` would make more sense?

**Comment by ysimonson** [comment]
Ping @ian-axelrod

**Comment by ian-axelrod** [comment]
It is mutually exclusive because there is a lock per queue, of which BoundedMutuallyExclusiveWaitQueue maintains multiple. The `Bounded` aspect refers to the total number of queues that can be locked at any one time.

**Comment by ysimonson** [comment]
But it's a read-write mutex lock. At the very least, it should follow the same naming convention as go's sync package, in which case it'd be `BoundedRWMutexWaitQueue`. Even then, though, it feels kinda wordy.

**Comment by ian-axelrod** [comment]
I do agree it feels wordy. Any suggestions on a succinct name that correctly communicates the mechanism?
